### ISSUE TITLE
请问如何适合使用 EAC-AL呢？

### ISSUE THREAD

**Issue by mrpersimmon** [newbee-ML/clustering-ensemble--EAC#1]

**Comment by newbee-ML** [comment]
很抱歉这么久才回复您的问题，您说的“EAC-AL”是指什么呢？这个工程是很久之前写的，我不记得有相关内容，麻烦您直接指明~

**Comment by mrpersimmon** [comment]
> 

EAC-AL 就是原论文中提到的在形成的新的共同关联矩阵上使用average-link层次聚类进行集成。

**Comment by mrpersimmon** [comment]
我将代码中的 Z = linkage(distance, 'single') ，修改为 Z = linkage(distance, 'average')，但是最终结果很糟糕，对这个部分很迷惑，原文中提到 AL 的效果是要比 SL 更好的。

**Comment by newbee-ML** [comment]
可能和具体数据有关，方法不可能一致好
